name: Plugins - CI
permissions: {}

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    name: CI
    uses: grafana/plugin-ci-workflows/.github/workflows/ci.yml@main
    with:
      plugin-version-suffix: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || '' }}
      run-playwright: true
      go-version: '1.24'
      golangci-lint-version: '1.64.6'
